apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analytics-report-pvc
  namespace: research
  labels:
    app: bifrost-analytics
    component: elementary-report
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
