"""Canonical Golden Source schema names for Research-owned feature tables.

Wave 6.4–6.6: single ``features`` schema with four-part table names
``{asset}_{stage}_{name}_{granularity}``.
"""

SCHEMA_FEATURES = "features"

# Wave RS-A — Hypothesis + Research workflow objects (Golden Source, D-RS-a).
SCHEMA_RESEARCH = "research"
TABLE_RESEARCH_HYPOTHESIS = f"{SCHEMA_RESEARCH}.hypothesis"

# Wave RS-C4 — event-driven backtest runs (colocated with hypotheses).
TABLE_RESEARCH_BACKTEST_RUN = f"{SCHEMA_RESEARCH}.backtest_run"

# Wave RS-E3 — AI draft inbox + action audit log (D-RS-E-e/g).
TABLE_RESEARCH_AI_ACTION_LOG = f"{SCHEMA_RESEARCH}.ai_action_log"
TABLE_RESEARCH_AI_DRAFT = f"{SCHEMA_RESEARCH}.ai_draft"
TABLE_RESEARCH_COPILOT_SESSION = f"{SCHEMA_RESEARCH}.copilot_session"

# --- Canonical table names (schema.table) ---
TABLE_OPTION_METRIC_ATM_IV_DAILY = f"{SCHEMA_FEATURES}.option_metric_atm_iv_daily"
TABLE_OPTION_METRIC_MAX_PAIN_DAILY = f"{SCHEMA_FEATURES}.option_metric_max_pain_daily"
TABLE_OPTION_METRIC_PCR_DAILY = f"{SCHEMA_FEATURES}.option_metric_pcr_daily"
TABLE_OPTION_METRIC_IV_PERCENTILE_DAILY = f"{SCHEMA_FEATURES}.option_metric_iv_percentile_daily"
TABLE_OPTION_METRIC_GEX_DAILY = f"{SCHEMA_FEATURES}.option_metric_gex_daily"
TABLE_OPTION_METRIC_GEX_INTRADAY = f"{SCHEMA_FEATURES}.option_metric_gex_intraday"
TABLE_OPTION_METRIC_GEX_LEVELS_DAILY = f"{SCHEMA_FEATURES}.option_metric_gex_levels_daily"
TABLE_OPTION_SURFACE_IV_DAILY = f"{SCHEMA_FEATURES}.option_surface_iv_daily"
TABLE_OPTION_FLOW_SENTIMENT_DAILY = f"{SCHEMA_FEATURES}.option_flow_sentiment_daily"
TABLE_OPTION_FLOW_MULTI_LEG_DAILY = f"{SCHEMA_FEATURES}.option_flow_multi_leg_daily"
TABLE_STOCK_SIGNAL_MOMENTUM_DAILY = f"{SCHEMA_FEATURES}.stock_signal_momentum_daily"
TABLE_STOCK_SIGNAL_SEPA_DAILY = f"{SCHEMA_FEATURES}.stock_signal_sepa_daily"
TABLE_EVENT_SIGNAL_RADAR_DAILY = f"{SCHEMA_FEATURES}.event_signal_radar_daily"
TABLE_STOCK_FORECAST_TERRAIN_DAILY = f"{SCHEMA_FEATURES}.stock_forecast_terrain_daily"
TABLE_STOCK_FORECAST_TERRAIN_INTRADAY = f"{SCHEMA_FEATURES}.stock_forecast_terrain_intraday"
TABLE_STOCK_FORECAST_SESSION = f"{SCHEMA_FEATURES}.stock_forecast_session"
TABLE_STOCK_FORECAST_HOURLY = f"{SCHEMA_FEATURES}.stock_forecast_hourly"
TABLE_STOCK_BACKTEST_SETTLEMENT = f"{SCHEMA_FEATURES}.stock_backtest_settlement"
TABLE_STOCK_BACKTEST_RESULTS_PERIOD = f"{SCHEMA_FEATURES}.stock_backtest_results_period"

# Partitioned option metric daily tables (for ensure_month_partitions)
OPTION_METRIC_PARTITIONED_TABLES = (
    "option_metric_max_pain_daily",
    "option_metric_atm_iv_daily",
    "option_metric_pcr_daily",
    "option_metric_iv_percentile_daily",
)

CANONICAL_FEATURE_TABLES = (
    TABLE_OPTION_METRIC_ATM_IV_DAILY,
    TABLE_OPTION_METRIC_MAX_PAIN_DAILY,
    TABLE_OPTION_METRIC_PCR_DAILY,
    TABLE_OPTION_METRIC_IV_PERCENTILE_DAILY,
    TABLE_OPTION_METRIC_GEX_DAILY,
    TABLE_OPTION_METRIC_GEX_INTRADAY,
    TABLE_OPTION_METRIC_GEX_LEVELS_DAILY,
    TABLE_OPTION_SURFACE_IV_DAILY,
    TABLE_OPTION_FLOW_SENTIMENT_DAILY,
    TABLE_OPTION_FLOW_MULTI_LEG_DAILY,
    TABLE_STOCK_SIGNAL_MOMENTUM_DAILY,
    TABLE_STOCK_SIGNAL_SEPA_DAILY,
    TABLE_EVENT_SIGNAL_RADAR_DAILY,
    TABLE_STOCK_FORECAST_TERRAIN_DAILY,
    TABLE_STOCK_FORECAST_TERRAIN_INTRADAY,
    TABLE_STOCK_FORECAST_SESSION,
    TABLE_STOCK_FORECAST_HOURLY,
    TABLE_STOCK_BACKTEST_SETTLEMENT,
    TABLE_STOCK_BACKTEST_RESULTS_PERIOD,
)

# Deprecated aliases — same canonical tables (gradual code migration)
TABLE_MOMENTUM_SCORE_DAILY = TABLE_STOCK_SIGNAL_MOMENTUM_DAILY
TABLE_SEPA_SCORE_DAILY = TABLE_STOCK_SIGNAL_SEPA_DAILY
TABLE_EVENT_RADAR = TABLE_EVENT_SIGNAL_RADAR_DAILY
TABLE_MARKET_TERRAIN_DAILY = TABLE_STOCK_FORECAST_TERRAIN_DAILY
TABLE_TERRAIN_INTRADAY = TABLE_STOCK_FORECAST_TERRAIN_INTRADAY
TABLE_FORECAST_SESSION = TABLE_STOCK_FORECAST_SESSION
TABLE_FORECAST_HOURLY = TABLE_STOCK_FORECAST_HOURLY
TABLE_FORECAST_SETTLEMENT = TABLE_STOCK_BACKTEST_SETTLEMENT
TABLE_BACKTEST_RESULTS = TABLE_STOCK_BACKTEST_RESULTS_PERIOD
